INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'PROFESSOR');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'TA');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'STUDENT');